// ELIJAY'S inventory lines from Excel (June 16) — no footwear
module.exports = [
  { name: 'Belt c', opening: 0, sales: 0, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Belt official', opening: 8, sales: 0, stockOut: 0, stockIn: 0, closing: 8 },
  { name: 'Suits', opening: 18, sales: 0, stockOut: 0, stockIn: 0, closing: 18 },
  { name: 'Official trousers', opening: 15, sales: 0, stockOut: 0, stockIn: 0, closing: 15 },
  { name: 'Jeans trousers', opening: 47, sales: 0, stockOut: 0, stockIn: 0, closing: 47 },
  { name: 'Polo Big', opening: 3, sales: 0, stockOut: 0, stockIn: 0, closing: 3 },
  { name: 'Polo T-shirts', opening: 95, sales: 0, stockOut: 0, stockIn: 0, closing: 95 },
  { name: 'Jacket exp', opening: 0, sales: 0, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Jacket light', opening: 0, sales: 0, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Jacket khaki', opening: 2, sales: 0, stockOut: 0, stockIn: 0, closing: 2 },
  { name: 'Sweater round', opening: 27, sales: 0, stockOut: 0, stockIn: 0, closing: 27 },
  { name: 'Sweater zip', opening: 8, sales: 0, stockOut: 0, stockIn: 0, closing: 8 },
  { name: 'Khaki exp', opening: 11, sales: 0, stockOut: 0, stockIn: 0, closing: 11 },
  { name: 'Khaki slim', opening: 167, sales: 0, stockOut: 0, stockIn: 0, closing: 167 },
  { name: 'Boxers', opening: 167, sales: 0, stockOut: 0, stockIn: 0, closing: 167 },
  { name: 'Socks Turkey', opening: 39, sales: 0, stockOut: 0, stockIn: 0, closing: 39 },
  { name: 'Socks', opening: 75, sales: 0, stockOut: 0, stockIn: 0, closing: 75 },
  { name: 'Official Floral', opening: 421, sales: 0, stockOut: 0, stockIn: 0, closing: 421 },
  { name: 'Jeans Shirts', opening: 73, sales: 0, stockOut: 0, stockIn: 0, closing: 73 },
  { name: 'Khaki Shirts', opening: 10, sales: 0, stockOut: 0, stockIn: 0, closing: 10 },
  { name: 'Linnen Shirts', opening: 10, sales: 0, stockOut: 0, stockIn: 0, closing: 10 },
  { name: 'Official Shirts', opening: 248, sales: 0, stockOut: 0, stockIn: 0, closing: 248 },
  { name: 'Vest', opening: 46, sales: 0, stockOut: 0, stockIn: 0, closing: 46 },
  { name: 'Caps', opening: 20, sales: 0, stockOut: 0, stockIn: 0, closing: 20 },
  { name: 'Ties', opening: 156, sales: 0, stockOut: 0, stockIn: 0, closing: 156 },
  { name: 'Scarfs', opening: 11, sales: 0, stockOut: 0, stockIn: 0, closing: 11 },
  { name: 'Jeans Shirts big', opening: 23, sales: 0, stockOut: 0, stockIn: 0, closing: 23 },
  { name: 'Jacket Turkey', opening: 64, sales: 0, stockOut: 0, stockIn: 0, closing: 64 },
  { name: 'Hankies', opening: 6, sales: 0, stockOut: 0, stockIn: 0, closing: 6 },
  { name: 'Official Sweater (T)', opening: 23, sales: 0, stockOut: 0, stockIn: 0, closing: 23 },
];
